export const LIGHT_THEME = {
  main_color: "#6c63ff",
  white: "#fff",
  sec_color: "#ffffff",
  sec_color2: "#494949ff",
  sec_color3: "#ffffff",
  border_color: "#c7c9c7",
  light_color: "#dddcfc",
  lighter_color: "#ffffff",
  green: "#4CAF50",
  red: "#F44336",
  red_light: "#ffdbdb",
  green_light: "#dbffeb",
  grey: "#7a7979ff",
};
export const DARK_THEME = {
  main_color: "#6c63ff",
  white: "#f5f5f5ff",
  sec_color: "#121212",
  sec_color2: "#d0cbcbff",
  sec_color3: "#1b1b1bff",
  border_color: "transparent",
  light_color: "#dddcfc",
  lighter_color: "#ffffff",
  green: "#4CAF50",
  red: "#F44336",
  red_light: "#ffdbdb",
  green_light: "#dbffeb",
  grey: "#AAAAAA",
};
