import { StyleSheet } from "react-native";

export const create_styles = (COLORS: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: COLORS.sec_color,
      padding: 20,
      paddingTop: 10,
    },
    header: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginTop: 15,
      paddingVertical: 5,
      paddingHorizontal: 15,
      elevation: 8,
      shadowColor: COLORS.border_color,
      backgroundColor: COLORS.sec_color,
      borderRadius: 10,
    },
    form: {
      width: "100%",
      borderRadius: 10,
      marginTop: 15,
      paddingHorizontal: 20,
      paddingBottom: 30,
      elevation: 8,
      shadowColor: COLORS.border_color,
      backgroundColor: COLORS.sec_color,
    },
    type_container: {
      marginTop: 20,
      flexDirection: "row",
      justifyContent: "space-between",
    },
    type_btn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 10,
      width: 140,
      borderRadius: 25,
      paddingVertical: 12,
      borderWidth: 1,
      borderStyle: "solid",
    },
    title_container: {
      marginTop: 20,
      flexDirection: "row",
      gap: 10,
      alignItems: "center",
      backgroundColor: COLORS.sec_color3,
      elevation: 5,
      shadowColor: COLORS.border_color,
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 7,
    },
    amount_inp_container: {
      flexDirection: "row",
      alignItems: "center",
      marginTop: 10,
      backgroundColor: COLORS.sec_color3,
      elevation: 5,
      shadowColor: COLORS.border_color,
      padding: 10,
      paddingHorizontal: 20,
      borderRadius: 10,
    },
    categ_container: {
      marginTop: 20,
      gap: 10,
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "flex-start",
    },
    categ: {
      flexDirection: "row",
      flexGrow: 1,
      gap: 10,
      alignItems: "center",
      backgroundColor: COLORS.sec_color3,
      elevation: 2,
      shadowColor: COLORS.border_color,
      padding: 10,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: COLORS.border_color,
      borderStyle: "solid",
    },
  });
